import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import HeroSection from '@/components/heroSection'
import Services from '@/components/services'
import Pricing from '@/components/pricing'
import About from '@/components/about'

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className=' '>
              <HeroSection />
              <About />
              <Services />
              {/* <Pricing /> */}
            </main>
        </>
    )
}
